//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 11:41:31 AM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwsbillpayment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwsbillpayment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwsbillpayment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaymentBillerResponse }
     * 
     */
    public PaymentBillerResponse createPaymentBillerResponse() {
        return new PaymentBillerResponse();
    }

    /**
     * Create an instance of {@link InqDebitBillPaymentResponse }
     * 
     */
    public InqDebitBillPaymentResponse createInqDebitBillPaymentResponse() {
        return new InqDebitBillPaymentResponse();
    }

    /**
     * Create an instance of {@link InqDebitBillPayment }
     * 
     */
    public InqDebitBillPayment createInqDebitBillPayment() {
        return new InqDebitBillPayment();
    }

    /**
     * Create an instance of {@link CommonParam2 }
     * 
     */
    public CommonParam2 createCommonParam2() {
        return new CommonParam2();
    }

    /**
     * Create an instance of {@link PaymentBiller }
     * 
     */
    public PaymentBiller createPaymentBiller() {
        return new PaymentBiller();
    }

}
