//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:25:04 PM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACCOUNTTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCOUNTTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FATYPEID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FATYPENAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCOUNTTYPE", propOrder = {
    "fatypeid",
    "fatypename"
})
public class ACCOUNTTYPE {

    @XmlElement(name = "FATYPEID")
    protected String fatypeid;
    @XmlElement(name = "FATYPENAME")
    protected String fatypename;

    /**
     * Gets the value of the fatypeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATYPEID() {
        return fatypeid;
    }

    /**
     * Sets the value of the fatypeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATYPEID(String value) {
        this.fatypeid = value;
    }

    /**
     * Gets the value of the fatypename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATYPENAME() {
        return fatypename;
    }

    /**
     * Sets the value of the fatypename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATYPENAME(String value) {
        this.fatypename = value;
    }

}
