//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:25:04 PM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inqDebitTopup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inqDebitTopup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commonParam" type="{http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.biller.ws.provider:BtpnBillerWsTopup}CommonParam2"/>
 *         &lt;element name="desc1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desc2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desc3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desc4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="debitAccount" type="{http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.biller.ws.provider:BtpnBillerWsTopup}debitAccount"/>
 *         &lt;element name="amountDenom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="topUpNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="institutionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inqDebitTopup", propOrder = {
    "commonParam",
    "desc1",
    "desc2",
    "desc3",
    "desc4",
    "debitAccount",
    "amountDenom",
    "topUpNumber",
    "productID",
    "institutionCode"
})
@XmlRootElement(name = "inqDebitTopup")
public class InqDebitTopup {

    @XmlElement(required = true, nillable = true)
    protected CommonParam2 commonParam;
    @XmlElement(required = true, nillable = true)
    protected String desc1;
    @XmlElement(required = true, nillable = true)
    protected String desc2;
    @XmlElement(required = true, nillable = true)
    protected String desc3;
    @XmlElement(required = true, nillable = true)
    protected String desc4;
    @XmlElement(required = true, nillable = true)
    protected DebitAccount debitAccount;
    @XmlElement(required = true, nillable = true)
    protected String amountDenom;
    @XmlElement(required = true, nillable = true)
    protected String topUpNumber;
    @XmlElement(required = true, nillable = true)
    protected String productID;
    @XmlElement(required = true, nillable = true)
    protected String institutionCode;

    /**
     * Gets the value of the commonParam property.
     * 
     * @return
     *     possible object is
     *     {@link CommonParam2 }
     *     
     */
    public CommonParam2 getCommonParam() {
        return commonParam;
    }

    /**
     * Sets the value of the commonParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonParam2 }
     *     
     */
    public void setCommonParam(CommonParam2 value) {
        this.commonParam = value;
    }

    /**
     * Gets the value of the desc1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * Sets the value of the desc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc1(String value) {
        this.desc1 = value;
    }

    /**
     * Gets the value of the desc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * Sets the value of the desc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc2(String value) {
        this.desc2 = value;
    }

    /**
     * Gets the value of the desc3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * Sets the value of the desc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc3(String value) {
        this.desc3 = value;
    }

    /**
     * Gets the value of the desc4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * Sets the value of the desc4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc4(String value) {
        this.desc4 = value;
    }

    /**
     * Gets the value of the debitAccount property.
     * 
     * @return
     *     possible object is
     *     {@link DebitAccount }
     *     
     */
    public DebitAccount getDebitAccount() {
        return debitAccount;
    }

    /**
     * Sets the value of the debitAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitAccount }
     *     
     */
    public void setDebitAccount(DebitAccount value) {
        this.debitAccount = value;
    }

    /**
     * Gets the value of the amountDenom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountDenom() {
        return amountDenom;
    }

    /**
     * Sets the value of the amountDenom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountDenom(String value) {
        this.amountDenom = value;
    }

    /**
     * Gets the value of the topUpNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopUpNumber() {
        return topUpNumber;
    }

    /**
     * Sets the value of the topUpNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopUpNumber(String value) {
        this.topUpNumber = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductID(String value) {
        this.productID = value;
    }

    /**
     * Gets the value of the institutionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionCode() {
        return institutionCode;
    }

    /**
     * Sets the value of the institutionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionCode(String value) {
        this.institutionCode = value;
    }

}
