//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:25:04 PM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InqDebitTopup }
     * 
     */
    public InqDebitTopup createInqDebitTopup() {
        return new InqDebitTopup();
    }

    /**
     * Create an instance of {@link CommonParam2 }
     * 
     */
    public CommonParam2 createCommonParam2() {
        return new CommonParam2();
    }

    /**
     * Create an instance of {@link DebitAccount }
     * 
     */
    public DebitAccount createDebitAccount() {
        return new DebitAccount();
    }

    /**
     * Create an instance of {@link CheckCustomerPackage }
     * 
     */
    public CheckCustomerPackage createCheckCustomerPackage() {
        return new CheckCustomerPackage();
    }

    /**
     * Create an instance of {@link InqDebitTopupResponse }
     * 
     */
    public InqDebitTopupResponse createInqDebitTopupResponse() {
        return new InqDebitTopupResponse();
    }

    /**
     * Create an instance of {@link TopupBillerResponse }
     * 
     */
    public TopupBillerResponse createTopupBillerResponse() {
        return new TopupBillerResponse();
    }

    /**
     * Create an instance of {@link TopupBiller }
     * 
     */
    public TopupBiller createTopupBiller() {
        return new TopupBiller();
    }

    /**
     * Create an instance of {@link CheckCustomerPackageResponse }
     * 
     */
    public CheckCustomerPackageResponse createCheckCustomerPackageResponse() {
        return new CheckCustomerPackageResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Balance }
     * 
     */
    public Balance createBalance() {
        return new Balance();
    }

    /**
     * Create an instance of {@link ACCOUNTTYPE }
     * 
     */
    public ACCOUNTTYPE createACCOUNTTYPE() {
        return new ACCOUNTTYPE();
    }

    /**
     * Create an instance of {@link PACKAGELIST }
     * 
     */
    public PACKAGELIST createPACKAGELIST() {
        return new PACKAGELIST();
    }

}
