//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:25:04 PM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RESPONSECODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUSTOMERCLASS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUSTOMERTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUSTOMERNBR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUSTOMERNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUSTOMERSTATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNTTYPE" type="{http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.biller.ws.provider:BtpnBillerWsTopup}ACCOUNTTYPE" maxOccurs="unbounded"/>
 *         &lt;element name="NUMACTIVEDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PACKAGELIST" type="{http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.biller.ws.provider:BtpnBillerWsTopup}PACKAGELIST" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response", propOrder = {
    "status",
    "responsecode",
    "customerclass",
    "customertype",
    "customernbr",
    "customername",
    "customerstatus",
    "accounttypes",
    "numactivedevice",
    "packagelists"
})
public class Response {

    @XmlElement(name = "STATUS")
    protected String status;
    @XmlElement(name = "RESPONSECODE")
    protected String responsecode;
    @XmlElement(name = "CUSTOMERCLASS")
    protected String customerclass;
    @XmlElement(name = "CUSTOMERTYPE")
    protected String customertype;
    @XmlElement(name = "CUSTOMERNBR")
    protected String customernbr;
    @XmlElement(name = "CUSTOMERNAME")
    protected String customername;
    @XmlElement(name = "CUSTOMERSTATUS")
    protected String customerstatus;
    @XmlElement(name = "ACCOUNTTYPE", required = true, nillable = true)
    protected List<ACCOUNTTYPE> accounttypes;
    @XmlElement(name = "NUMACTIVEDEVICE", required = true)
    protected String numactivedevice;
    @XmlElement(name = "PACKAGELIST", required = true, nillable = true)
    protected List<PACKAGELIST> packagelists;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the responsecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESPONSECODE() {
        return responsecode;
    }

    /**
     * Sets the value of the responsecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESPONSECODE(String value) {
        this.responsecode = value;
    }

    /**
     * Gets the value of the customerclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERCLASS() {
        return customerclass;
    }

    /**
     * Sets the value of the customerclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERCLASS(String value) {
        this.customerclass = value;
    }

    /**
     * Gets the value of the customertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERTYPE() {
        return customertype;
    }

    /**
     * Sets the value of the customertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERTYPE(String value) {
        this.customertype = value;
    }

    /**
     * Gets the value of the customernbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERNBR() {
        return customernbr;
    }

    /**
     * Sets the value of the customernbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERNBR(String value) {
        this.customernbr = value;
    }

    /**
     * Gets the value of the customername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERNAME() {
        return customername;
    }

    /**
     * Sets the value of the customername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERNAME(String value) {
        this.customername = value;
    }

    /**
     * Gets the value of the customerstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERSTATUS() {
        return customerstatus;
    }

    /**
     * Sets the value of the customerstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERSTATUS(String value) {
        this.customerstatus = value;
    }

    /**
     * Gets the value of the accounttypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accounttypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACCOUNTTYPES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACCOUNTTYPE }
     * 
     * 
     */
    public List<ACCOUNTTYPE> getACCOUNTTYPES() {
        if (accounttypes == null) {
            accounttypes = new ArrayList<ACCOUNTTYPE>();
        }
        return this.accounttypes;
    }

    /**
     * Gets the value of the numactivedevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMACTIVEDEVICE() {
        return numactivedevice;
    }

    /**
     * Sets the value of the numactivedevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMACTIVEDEVICE(String value) {
        this.numactivedevice = value;
    }

    /**
     * Gets the value of the packagelists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagelists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKAGELISTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PACKAGELIST }
     * 
     * 
     */
    public List<PACKAGELIST> getPACKAGELISTS() {
        if (packagelists == null) {
            packagelists = new ArrayList<PACKAGELIST>();
        }
        return this.packagelists;
    }

}
