//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:25:04 PM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_biller_ws_provider.btpnbillerwstopup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for topupBiller complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="topupBiller">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commonParam" type="{http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.biller.ws.provider:BtpnBillerWsTopup}CommonParam2"/>
 *         &lt;element name="pinType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pinValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billerCustNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="institutionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processingCodeBiller" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "topupBiller", propOrder = {
    "commonParam",
    "pinType",
    "pinValue",
    "accountNo",
    "billerCustNo",
    "institutionCode",
    "productID",
    "attribute1",
    "attribute2",
    "attribute3",
    "processingCodeBiller"
})
@XmlRootElement(name = "topupBiller")
public class TopupBiller {

    @XmlElement(required = true, nillable = true)
    protected CommonParam2 commonParam;
    @XmlElement(required = true, nillable = true)
    protected String pinType;
    @XmlElement(required = true, nillable = true)
    protected String pinValue;
    @XmlElement(required = true, nillable = true)
    protected String accountNo;
    @XmlElement(required = true, nillable = true)
    protected String billerCustNo;
    @XmlElement(required = true, nillable = true)
    protected String institutionCode;
    @XmlElement(required = true, nillable = true)
    protected String productID;
    @XmlElement(required = true, nillable = true)
    protected String attribute1;
    @XmlElement(required = true, nillable = true)
    protected String attribute2;
    @XmlElement(required = true, nillable = true)
    protected String attribute3;
    @XmlElement(required = true, nillable = true)
    protected String processingCodeBiller;

    /**
     * Gets the value of the commonParam property.
     * 
     * @return
     *     possible object is
     *     {@link CommonParam2 }
     *     
     */
    public CommonParam2 getCommonParam() {
        return commonParam;
    }

    /**
     * Sets the value of the commonParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonParam2 }
     *     
     */
    public void setCommonParam(CommonParam2 value) {
        this.commonParam = value;
    }

    /**
     * Gets the value of the pinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinType() {
        return pinType;
    }

    /**
     * Sets the value of the pinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinType(String value) {
        this.pinType = value;
    }

    /**
     * Gets the value of the pinValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinValue() {
        return pinValue;
    }

    /**
     * Sets the value of the pinValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinValue(String value) {
        this.pinValue = value;
    }

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the billerCustNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerCustNo() {
        return billerCustNo;
    }

    /**
     * Sets the value of the billerCustNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerCustNo(String value) {
        this.billerCustNo = value;
    }

    /**
     * Gets the value of the institutionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionCode() {
        return institutionCode;
    }

    /**
     * Sets the value of the institutionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionCode(String value) {
        this.institutionCode = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductID(String value) {
        this.productID = value;
    }

    /**
     * Gets the value of the attribute1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * Sets the value of the attribute1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribute1(String value) {
        this.attribute1 = value;
    }

    /**
     * Gets the value of the attribute2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * Sets the value of the attribute2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribute2(String value) {
        this.attribute2 = value;
    }

    /**
     * Gets the value of the attribute3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * Sets the value of the attribute3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribute3(String value) {
        this.attribute3 = value;
    }

    /**
     * Gets the value of the processingCodeBiller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingCodeBiller() {
        return processingCodeBiller;
    }

    /**
     * Sets the value of the processingCodeBiller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingCodeBiller(String value) {
        this.processingCodeBiller = value;
    }

}
