//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 11:41:31 AM ICT 
//


package id.co.btpn.corp.dev.appmdwdev02.com_btpn_emoney_ws.wowtransferservices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.btpn.corp.dev.appmdwdev02.com_btpn_emoney_ws.wowtransferservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.btpn.corp.dev.appmdwdev02.com_btpn_emoney_ws.wowtransferservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InquiryDebitFundTransferResponse }
     * 
     */
    public InquiryDebitFundTransferResponse createInquiryDebitFundTransferResponse() {
        return new InquiryDebitFundTransferResponse();
    }

    /**
     * Create an instance of {@link InquiryDebitFundTransfer }
     * 
     */
    public InquiryDebitFundTransfer createInquiryDebitFundTransfer() {
        return new InquiryDebitFundTransfer();
    }

    /**
     * Create an instance of {@link CommonParam2 }
     * 
     */
    public CommonParam2 createCommonParam2() {
        return new CommonParam2();
    }

    /**
     * Create an instance of {@link FundTransfer }
     * 
     */
    public FundTransfer createFundTransfer() {
        return new FundTransfer();
    }

    /**
     * Create an instance of {@link FundTransferResponse }
     * 
     */
    public FundTransferResponse createFundTransferResponse() {
        return new FundTransferResponse();
    }

}
