//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 11:41:31 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://APPMDWDEV02.dev.corp.btpn.co.id/com.btpn.emoney.ws:wowAccountServices")
package id.co.btpn.corp.dev.appmdwdev02.com_btpn_emoney_ws.wowaccountservices;
